version: "3"
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-GDR1-ubuntu-16.04
    hostname: sql-server
    container_name: sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Str0ngPa$$w0rd
